In [1]:
import time
from dataclasses import dataclass, field
import heapq
from collections import defaultdict, deque
import random
import pandas as pd
import itertools
from order_book import MatchingEngine, Order, OrderBook

In [2]:
matching_engine = MatchingEngine()

for i in range(100000):
    symbol = random.choice(["SPY", "QQQ"])
    direction = random.choice(["buy", "sell"])
    type = random.choice(["limit"])
    qty = random.randint(0, 100)
    price = random.randint(90, 110)
    order = Order(symbol, direction, type, price, qty)
    matching_engine.process_order(order)

In [3]:
matching_engine.get_trades()

,symbol,trade_id,buy_order_id,sell_order_id,price_ticks,quantity,timestamp
0,QQQ,1,7,6,90,7,2026-05-08 00:20:38.976164+00:00
1,QQQ,4,10,6,90,80,2026-05-08 00:20:38.976187+00:00
2,QQQ,5,11,6,90,4,2026-05-08 00:20:38.976191+00:00
3,QQQ,6,11,5,91,49,2026-05-08 00:20:38.976193+00:00
4,QQQ,7,13,5,91,24,2026-05-08 00:20:38.976200+00:00
...,...,...,...,...,...,...,...
78382,SPY,78378,64756,99990,94,27,2026-05-08 00:20:39.209184+00:00
78383,SPY,78379,64824,99990,94,17,2026-05-08 00:20:39.209184+00:00
78384,SPY,78381,99993,99991,95,84,2026-05-08 00:20:39.209190+00:00
78385,SPY,78382,64824,99994,94,68,2026-05-08 00:20:39.209191+00:00
78386,SPY,78383,99997,99991,95,16,2026-05-08 00:20:39.209197+00:00

In [155]:
print(matching_engine.best_ask("QQQ"))

104

In [ ]:
trades = book.get_trades()
trades

       trade_id  buy_order_id  sell_order_id  price  quantity     timestamp
0             1             8              1     98         5  1.778120e+09
1             2             8              2    103        13  1.778120e+09
2             3             8             10    106        17  1.778120e+09
3             4            11             12    108        51  1.778120e+09
4             5             8             12    106         8  1.778120e+09
...         ...           ...            ...    ...       ...           ...
78336     78337         99961          99998    100        23  1.778120e+09
78337     78338         99999          99993    101        25  1.778120e+09
78338     78339         99999          99991    103        17  1.778120e+09
78339     78340         99999          73972    106         2  1.778120e+09
78340     78341         99999          74004    106        27  1.778120e+09

[78341 rows x 6 columns]